In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
import glob
glob.glob('MALARIA EDA/Malaria data/Malaria data*.csv')

[]

In [4]:
df1 = pd.read_csv('MALARIA EDA/Malaria data/Malaria data 2020.csv')
df1.head(2)

FileNotFoundError: [Errno 2] No such file or directory: 'MALARIA EDA/Malaria data/Malaria data 2020.csv'

In [5]:
df1 = pd.read_csv('MALARIA EDA/Malaria data/Malaria data 2021.csv')
df1.head(2)

,Region,District,0-28 DAYS FEMALE,0-28 DAYS MALE,0-28 DAYS TOTAL,10-19 YEARS FEMALE,10-19 YEARS MALE,10-19 YRS TOTAL,20+ YRS FEMALE,20+ YRS MALE,...,<5YRS MALE TOTAL,< 5YRS GRAND TOTAL,POPULATION IN 2014,POPULATION IN 2024,AREA(Km2),ANNUAL GROWTH RATE[Pt​=P0​×(1+r)t],TOTAL POPULATION,POPULATION DENSITY(People per km2),CORDINATES (LATITUDE ° N),CORDINATES (LONGITUDE ° E)
0,Karamoja,Abim District,2.0,5.0,7.0,13939.0,6695.0,20634.0,15856.0,7109.0,...,13473.0,30071.0,107966.0,144084.0,2301.0,1.029278437,132134.7761,57.42493529,2.7067,33.6595
1,Acholi,Acholi,368.0,310.0,678.0,246462.0,132169.0,378631.0,228667.0,82226.0,...,125118.0,320816.0,1500762.0,2044355.0,28522.0,1.031393639,1863300.782,65.32854577,NaN,NaN

In [6]:
df1 = pd.read_csv('MALARIA EDA/Malaria data/Malaria data 2022.csv')
df1.head(2)

,Region,District,0-28 DAYS FEMALE,0-28 DAYS MALE,0-28 DAYS TOTAL,10-19 YEARS FEMALE,10-19 YEARS MALE,10-19YRS TOTAL,20+ YRS FEMALE,20+ YRS MALE,...,POPULATION IN 2024,AREA(Km2),ANNUAL GROWTH RATE[Pt​=P0​×(1+r)t],TOTAL POPULATION,POPULATION DENSITY(People per km2),CORDINATES (LATITUDE ° N),CORDINATES (LONGITUDE ° E),Unnamed: 64,Unnamed: 65,Unnamed: 66
0,Karamoja,Abim District,12,18,30,14866,8361,23227,15518,7577,...,10358,22122,107966.0,144084.0,2301.0,1.029278437,136003.4758,59.10624763,2.7067,33.6595
1,Acholi,Acholi,528,487,1015,336742,203007,539749,324222,111643,...,174691,362389,1500762.0,2044355.0,28522.0,1.031393639,1921796.575,67.37944658,NaN,NaN

In [7]:
df1 = pd.read_csv('MALARIA EDA/Malaria data/Malaria data 2023.csv')
df1.head(2)

,Region,District,0-28 DAYS FEMALE,0-28 DAYS MALE,0-28 DAYS TOTAL,10-19 YEARS FEMALE,10-19 YEARS MALE,10-19YRS TOTAL,20+ YRS FEMALE,20+ YRS MALE,...,<5YRS MALE TOTAL,< 5YRS GRAND TOTAL,POPULATION IN 2014,POPULATION IN 2024,AREA(Km2),ANNUAL GROWTH RATE[Pt​=P0​×(1+r)t],TOTAL POPULATION,POPULATION DENSITY(People per km2),CORDINATES (LATITUDE ° N),CORDINATES (LONGITUDE ° E)
0,Karamoja,Abim District,6,7,13,13832,7550,21382,13164,6351,...,8762,17992,107966.0,144084.0,2301.0,1.029278437,139985.445,60.83678617,2.7067,33.6595
1,Acholi,Acholi,383,335,718,298281,181956,480237,277994,94253,...,151443,286282,1500762.0,2044355.0,28522.0,1.031393639,1982128.764,69.49473263,NaN,NaN

In [5]:
df1 = pd.read_csv('MALARIA EDA/Malaria data/Malaria data 2024.csv')
df1.head(2)

FileNotFoundError: [Errno 2] No such file or directory: 'MALARIA EDA/Malaria data/Malaria data 2024.csv'

In [26]:
df1.shape

(162, 65)

In [ ]:
df1.info()

In [11]:
all_dfs = []
for one_filename in glob.glob('MALARIA EDA/Malaria data/Malaria data*.csv'):
    print(f'Loading {one_filename}')
master_df = pd.read_csv(one_filename)

Loading MALARIA EDA/Malaria data\Malaria data 2020.csv
Loading MALARIA EDA/Malaria data\Malaria data 2021.csv
Loading MALARIA EDA/Malaria data\Malaria data 2022.csv
Loading MALARIA EDA/Malaria data\Malaria data 2023.csv
Loading MALARIA EDA/Malaria data\Malaria data 2024.csv

In [12]:
master_df.head(5)

,Region,District,0-28 DAYS FEMALE,0-28 DAYS MALE,0-28 DAYS TOTAL,10-19 YEARS FEMALE,10-19 YEARS MALE,10-19YRS TOTAL,20+ YRS FEMALE,20+ YRS MALE,...,<5YRS MALE TOTAL,< 5YRS GRAND TOTAL,POPULATION IN 2014,POPULATION IN 2024,AREA(Km2),ANNUAL GROWTH RATE[Pt​=P0​×(1+r)t],TOTAL POPULATION,POPULATION DENSITY(People per km2),CORDINATES (LATITUDE ° N),CORDINATES (LONGITUDE ° E)
0,Karamoja,Abim District,8,9,17.0,15577.0,8665,25223.0,15624.0,5949,...,8332.0,17562.0,107966.0,144084.0,2301.0,1.029278437,144084,62.61799218,2.7067,33.6595
1,Acholi,Acholi,266,222,488.0,263063.0,157299,580185.0,250568.0,86817,...,126811.0,261650.0,1500762.0,2044355.0,28522.0,1.031393639,2044355,71.67642522,NaN,NaN
2,West Nile,Adjumani District,43,32,75.0,24233.0,18864,120987.0,25366.0,11574,...,12203.0,24158.0,107966.0,144084.0,2301.0,1.029278437,144084,62.61799218,3.2549,31.7195
3,Acholi,Agago District,35,15,50.0,50050.0,28714,105379.0,48751.0,14387,...,22495.0,46761.0,227792.0,307235.0,3493.0,1.03037004,307235,87.95734326,2.9251,33.3486
4,Lango,Alebtong District,16,11,27.0,20209.0,9620,10961.0,25206.0,6647,...,11167.0,23228.0,227541.0,283509.0,1534.0,1.022234935,283509,184.8168188,2.2914,33.2139

In [ ]:
df1.info()

In [11]:
len(master_df)

199

In [14]:
master_df['GRAND TOTAL CASES'].value_counts()

GRAND TOTAL CASES
208345      2
1659514     1
326452      1
272657      1
35880       1
           ..
285484      1
2072775     1
411696      1
78414       1
25562132    1
Name: count, Length: 161, dtype: int64

In [62]:
import pandas as pd
import os

all_dfs = []
years = [2020, 2021, 2022, 2023, 2024]

base_dir = "./Malaria data"  

for year in years:
    file_path = os.path.join(base_dir, f"Malaria data {year}.csv")
    
    df = pd.read_csv(file_path)
    
    # # Drop fully empty rows/cols (optional)
    # df = df.dropna(axis=0, how="all").dropna(axis=1, how="all")
    
    # Clean headers (optional)
    df.columns = df.columns.str.strip()
    
    # Add Year column
    df["Year"] = year
    
    all_dfs.append(df)

# Combine everything into one master DF
master_df = pd.concat(all_dfs, ignore_index=True)

FileNotFoundError: [Errno 2] No such file or directory: './Malaria data\\Malaria data 2020.csv'

In [40]:
import pandas as pd

all_dfs = []
years = [2020, 2021, 2022, 2023, 2024]

for year in years:
    file_path = f"MALARIA EDA/Malaria data {year}.csv"
    
dfs = []
for file in all_files:
    df = pd.read_csv(file)
    df = clean_columns(df)
    dfs.append(df)
    
    # Drop fully empty rows/cols
    #df = df.dropna(axis=0, how="all").dropna(axis=1, how="all")
    
    # Clean headers (remove spaces)
    df.columns = df.columns.str.strip()
    
    # Add Year column
    df["Year"] = year
    
    all_dfs.append(df)

# Combine
master_df = pd.concat(all_dfs, ignore_index=True)

In [40]:
import pandas as pd

all_dfs = []
years = [2020, 2021, 2022, 2023, 2024]

for year in years:
    file_path = f"MALARIA EDA/Malaria data {year}.csv"
    
dfs = []
for file in all_files:
    df = pd.read_csv(file)
    df = clean_columns(df)
    dfs.append(df)
    
    # Drop fully empty rows/cols
    #df = df.dropna(axis=0, how="all").dropna(axis=1, how="all")
    
    # Clean headers (remove spaces)
    df.columns = df.columns.str.strip()
    
    # Add Year column
    df["Year"] = year
    
    all_dfs.append(df)

# Combine
master_df = pd.concat(all_dfs, ignore_index=True)

In [63]:
import pandas as pd

all_dfs = []
years = [2020, 2021, 2022, 2023, 2024]

for year in years:
    file_path = f"MALARIA EDA/Malaria data {year}.csv"
    
dfs = []
for file in all_files:
    df = pd.read_csv(file)
    df = clean_columns(df)
    dfs.append(df)
    
    # Drop fully empty rows/cols
    #df = df.dropna(axis=0, how="all").dropna(axis=1, how="all")
    
    # Clean headers (remove spaces)
    df.columns = df.columns.str.strip()
    
    # Add Year column
    df["Year"] = year
    
    all_dfs.append(df)

# Combine
master_df = pd.concat(all_dfs, ignore_index=True)

In [ ]:
master_df.info()

In [64]:
import glob
import pandas as pd

def clean_columns(df):
    df.columns = df.columns.str.strip()  # remove leading/trailing spaces
    df.columns = df.columns.str.replace(r"\s+", " ", regex=True)  # normalize multiple spaces to one
    return df

# Collect all CSVs
all_files = glob.glob("MALARIA EDA/Malaria data/*.csv")

dfs = []
for file in all_files:
    df = pd.read_csv(file)
    df = clean_columns(df)
    
 # Extract year from file name
year = os.path.splitext(os.path.basename(file))[0].split()[-1]
df["Year"] = int(year)

dfs.append(df)

#Combine into one master DataFrame
master_df = pd.concat(dfs, ignore_index=True)

print(master_df[["Year"]].head(20))
print(master_df.columns.tolist())

    Year
0   2024
1   2024
2   2024
3   2024
4   2024
5   2024
6   2024
7   2024
8   2024
9   2024
10  2024
11  2024
12  2024
13  2024
14  2024
15  2024
16  2024
17  2024
18  2024
19  2024
['Region', 'District', '0-28 DAYS FEMALE', '0-28 DAYS MALE', '0-28 DAYS TOTAL', '10-19 YEARS FEMALE', '10-19 YEARS MALE', '10-19YRS TOTAL', '20+ YRS FEMALE', '20+ YRS MALE', '20+ YRS TOTAL', '5-9YRS FEMALE', '5-9YRS MALE', '5-9YRS TOTAL', '29 DAYS-4YRS FEMALE', '29DAYS - 4YRS MALE', '29 DAYS - 4YRS TOTAL', '0-28 DAYS (B/S & RDT) FEMALE', '0-28 DAYS (B/S & RDT) MALE', '0-28 DAYS (B/S & RDT) TOTAL', '10-19 YRS (B/S & RDT) FEMALE', '10-19 YRS (B/S & RDT) MALE', '10-19 YRS (B/S & RDT) TOTAL', '20+ (B/S &RDT) FEMALE', '20+ (B/S & RDT) MALE', '20 + (B/S & RDT) TOTAL', '29DAYS-4YRS (B/S & RDT) FEMALE', '29DAYS-4YRS (B/S & RDT) MALE', '29DAYS-4 YRS (B/S & RDT) TOTAL', '5-9YRS (B/S & RDT) FEMALE', '5-9YRS (B/S & RDT) MALE', '5-9YRS (B/S & RDT) TOTAL', '0-28 DAYS FEMALE CT', '0-28 DAYS MALE CT', '0-28 DAYS TOTAL CT', '10-19 YRS FEMALE CT', '10-19 YRS MALE CT', '10-19 YRS CT TOTAL', '20 + YRS FEMALE CT', '20 + YRS MALE CT', '20 + YRS CT TOTAL', '29DAYS - 4YRS FEMALE CT', '29 DAYS - 4YRS MALE CT', '29 DAYS - 4YRS CT TOTAL', '5-9YRS FEMALE CT', '5-9YRS MALE CT', '5-9YRS CT TOTAL', 'PREG 10-19YRS', 'PREG 20 + YRS', 'TOTAL PREG', 'TOTAL CASES FEMALE', 'TOTAL CASES MALE', 'GRAND TOTAL CASES', '<5YRS FEMALES TOTAL', '<5YRS MALE TOTAL', '< 5YRS GRAND TOTAL', 'POPULATION IN 2014', 'POPULATION IN 2024', 'AREA(Km2)', 'ANNUAL GROWTH RATE[Pt\u200b=P0\u200b×(1+r)t]', 'TOTAL POPULATION', 'POPULATION DENSITY(People per km2)', 'CORDINATES (LATITUDE ° N)', 'CORDINATES (LONGITUDE ° E)', 'Year']

In [64]:
import glob
import pandas as pd

def clean_columns(df):
    df.columns = df.columns.str.strip()  # remove leading/trailing spaces
    df.columns = df.columns.str.replace(r"\s+", " ", regex=True)  # normalize multiple spaces to one
    return df

# Collect all CSVs
all_files = glob.glob("MALARIA EDA/Malaria data/*.csv")

dfs = []
for file in all_files:
    df = pd.read_csv(file)
    df = clean_columns(df)
    
 # Extract year from file name
year = os.path.splitext(os.path.basename(file))[0].split()[-1]
df["Year"] = int(year)

dfs.append(df)

#Combine into one master DataFrame
master_df = pd.concat(dfs, ignore_index=True)

print(master_df[["Year"]].head(20))
print(master_df.columns.tolist())

    Year
0   2024
1   2024
2   2024
3   2024
4   2024
5   2024
6   2024
7   2024
8   2024
9   2024
10  2024
11  2024
12  2024
13  2024
14  2024
15  2024
16  2024
17  2024
18  2024
19  2024
['Region', 'District', '0-28 DAYS FEMALE', '0-28 DAYS MALE', '0-28 DAYS TOTAL', '10-19 YEARS FEMALE', '10-19 YEARS MALE', '10-19YRS TOTAL', '20+ YRS FEMALE', '20+ YRS MALE', '20+ YRS TOTAL', '5-9YRS FEMALE', '5-9YRS MALE', '5-9YRS TOTAL', '29 DAYS-4YRS FEMALE', '29DAYS - 4YRS MALE', '29 DAYS - 4YRS TOTAL', '0-28 DAYS (B/S & RDT) FEMALE', '0-28 DAYS (B/S & RDT) MALE', '0-28 DAYS (B/S & RDT) TOTAL', '10-19 YRS (B/S & RDT) FEMALE', '10-19 YRS (B/S & RDT) MALE', '10-19 YRS (B/S & RDT) TOTAL', '20+ (B/S &RDT) FEMALE', '20+ (B/S & RDT) MALE', '20 + (B/S & RDT) TOTAL', '29DAYS-4YRS (B/S & RDT) FEMALE', '29DAYS-4YRS (B/S & RDT) MALE', '29DAYS-4 YRS (B/S & RDT) TOTAL', '5-9YRS (B/S & RDT) FEMALE', '5-9YRS (B/S & RDT) MALE', '5-9YRS (B/S & RDT) TOTAL', '0-28 DAYS FEMALE CT', '0-28 DAYS MALE CT', '0-28 DAYS TOTAL CT', '10-19 YRS FEMALE CT', '10-19 YRS MALE CT', '10-19 YRS CT TOTAL', '20 + YRS FEMALE CT', '20 + YRS MALE CT', '20 + YRS CT TOTAL', '29DAYS - 4YRS FEMALE CT', '29 DAYS - 4YRS MALE CT', '29 DAYS - 4YRS CT TOTAL', '5-9YRS FEMALE CT', '5-9YRS MALE CT', '5-9YRS CT TOTAL', 'PREG 10-19YRS', 'PREG 20 + YRS', 'TOTAL PREG', 'TOTAL CASES FEMALE', 'TOTAL CASES MALE', 'GRAND TOTAL CASES', '<5YRS FEMALES TOTAL', '<5YRS MALE TOTAL', '< 5YRS GRAND TOTAL', 'POPULATION IN 2014', 'POPULATION IN 2024', 'AREA(Km2)', 'ANNUAL GROWTH RATE[Pt\u200b=P0\u200b×(1+r)t]', 'TOTAL POPULATION', 'POPULATION DENSITY(People per km2)', 'CORDINATES (LATITUDE ° N)', 'CORDINATES (LONGITUDE ° E)', 'Year']

In [41]:
master_df

,Region,District,0-28 DAYS FEMALE,0-28 DAYS MALE,0-28 DAYS TOTAL,10-19 YEARS FEMALE,10-19 YEARS MALE,10-19YRS TOTAL,20+ YRS FEMALE,20+ YRS MALE,...,POPULATION DENSITY(People per km2),CORDINATES (LATITUDE ° N),CORDINATES (LONGITUDE ° E),Year,10-19 YRS TOTAL,29DAYS-4YRS MALE,20+ (B/S &RDT) MALE,Unnamed: 64,Unnamed: 65,Unnamed: 66
0,Karamoja,Abim District,6,7,13.0,16161.0,9062,25223.0,16507.0,8054,...,55.79144888,2.7067,33.6595,2024,NaN,NaN,NaN,NaN,NaN,NaN
1,Acholi,Acholi,316,338,654.0,365422.0,214763,580185.0,456269.0,123147,...,63.34007043,NaN,NaN,2024,NaN,NaN,NaN,NaN,NaN,NaN
2,West Nile,Adjumani District,14,10,24.0,68996.0,51991,120987.0,60160.0,28387,...,55.79144888,3.2549,31.7195,2024,NaN,NaN,NaN,NaN,NaN,NaN
3,Acholi,Agago District,46,66,112.0,66256.0,39123,105379.0,58935.0,20260,...,78.0367573,2.9251,33.3486,2024,NaN,NaN,NaN,NaN,NaN,NaN
4,Lango,Alebtong District,3,5,8.0,7110.0,3851,10961.0,9974.0,3515,...,169.253873,2.2914,33.2139,2024,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
843,NaN,NaN,NaN,NaN,NaN,NaN,Kigezi,NaN,NaN,Kigezi,...,NaN,NaN,NaN,2024,NaN,NaN,NaN,NaN,NaN,NaN
844,NaN,NaN,NaN,NaN,NaN,NaN,Karamoja,NaN,NaN,Karamoja,...,NaN,NaN,NaN,2024,NaN,NaN,NaN,NaN,NaN,NaN
845,NaN,NaN,NaN,NaN,NaN,NaN,Teso,NaN,NaN,Teso,...,NaN,NaN,NaN,2024,NaN,NaN,NaN,NaN,NaN,NaN
846,NaN,NaN,NaN,NaN,NaN,NaN,Tooro,NaN,NaN,Tooro,...,NaN,NaN,NaN,2024,NaN,NaN,NaN,NaN,NaN,NaN
847,NaN,NaN,NaN,NaN,NaN,NaN,SUM,NaN,NaN,NaN,...,NaN,NaN,NaN,2024,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
master_df.head(5)

,Region,District,0-28 DAYS FEMALE,0-28 DAYS MALE,0-28 DAYS TOTAL,10-19 YEARS FEMALE,10-19 YEARS MALE,10-19YRS TOTAL,20+ YRS FEMALE,20+ YRS MALE,...,<5YRS MALE TOTAL,< 5YRS GRAND TOTAL,AREA(Km2),TOTAL POPULATION,POPULATION DENSITY(People per km2),CORDINATES (LATITUDE ° N),CORDINATES (LONGITUDE ° E),10-19 YRS TOTAL,29DAYS-4YRS MALE,20+ (B/S &RDT) MALE
0,Karamoja,Abim District,6,7,13.0,16161.0,9062,25223.0,16507.0,8054,...,15199.0,31801.0,2301.0,128376.1239,55.79144888,2.7067,33.6595,NaN,NaN,NaN
1,Acholi,Acholi,316,338,654.0,365422.0,214763,580185.0,456269.0,123147,...,185689.0,381335.0,28522.0,1806585.489,63.34007043,NaN,NaN,NaN,NaN,NaN
2,West Nile,Adjumani District,14,10,24.0,68996.0,51991,120987.0,60160.0,28387,...,43291.0,87673.0,2301.0,128376.1239,55.79144888,3.2549,31.7195,NaN,NaN,NaN
3,Acholi,Agago District,46,66,112.0,66256.0,39123,105379.0,58935.0,20260,...,32950.0,67991.0,3493.0,272582.3933,78.0367573,2.9251,33.3486,NaN,NaN,NaN
4,Lango,Alebtong District,3,5,8.0,7110.0,3851,10961.0,9974.0,3515,...,4274.0,8806.0,1534.0,259635.4412,169.253873,2.2914,33.2139,NaN,NaN,NaN

In [ ]:
master_df.info()

In [ ]:
master_df['Unnamed: 65'].head(20)

In [83]:
# Creating a Wrangle Function
# Dropping some columns
master_df.drop( columns = ["POPULATION IN 2014", "POPULATION IN 2024", 
                           "ANNUAL GROWTH RATE[Pt​=P0​×(1+r)t]", "Unnamed: 64", 
                           "Unnamed: 65", "Unnamed: 66", "ANNUAL GROWTH RATE[Pt​=P0​×(1+r)t]"], inplace = True)

In [44]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 848 entries, 0 to 847
Data columns (total 65 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Region                              805 non-null    object
 1   District                            810 non-null    object
 2   0-28 DAYS FEMALE                    810 non-null    object
 3   0-28 DAYS MALE                      826 non-null    object
 4   0-28 DAYS TOTAL                     826 non-null    float64
 5   10-19 YEARS FEMALE                  809 non-null    float64
 6   10-19 YEARS MALE                    842 non-null    object
 7   10-19YRS TOTAL                      648 non-null    float64
 8   20+ YRS FEMALE                      809 non-null    float64
 9   20+ YRS MALE                        841 non-null    object
 10  20+ YRS TOTAL                       842 non-null    float64
 11  5-9YRS FEMALE                       808 non-null    float64
 12  5-9YRS MALE                         807 non-null    float64
 13  5-9YRS TOTAL                        809 non-null    float64
 14  29 DAYS-4YRS FEMALE                 809 non-null    float64
 15  29DAYS - 4YRS MALE                  647 non-null    float64
 16  29 DAYS - 4YRS TOTAL                810 non-null    float64
 17  0-28 DAYS (B/S & RDT) FEMALE        809 non-null    float64
 18  0-28 DAYS (B/S & RDT) MALE          808 non-null    float64
 19  0-28 DAYS (B/S & RDT) TOTAL         807 non-null    float64
 20  10-19 YRS (B/S & RDT) FEMALE        809 non-null    float64
 21  10-19 YRS (B/S & RDT) MALE          809 non-null    float64
 22  10-19 YRS (B/S & RDT) TOTAL         807 non-null    float64
 23  20+ (B/S &RDT) FEMALE               807 non-null    float64
 24  20+ (B/S & RDT) MALE                645 non-null    float64
 25  20 + (B/S & RDT) TOTAL              806 non-null    float64
 26  29DAYS-4YRS (B/S & RDT) FEMALE      809 non-null    float64
 27  29DAYS-4YRS (B/S & RDT) MALE        809 non-null    float64
 28  29DAYS-4 YRS (B/S & RDT) TOTAL      807 non-null    float64
 29  5-9YRS (B/S & RDT) FEMALE           809 non-null    float64
 30  5-9YRS (B/S & RDT) MALE             809 non-null    float64
 31  5-9YRS (B/S & RDT) TOTAL            808 non-null    float64
 32  0-28 DAYS FEMALE CT                 809 non-null    float64
 33  0-28 DAYS MALE CT                   809 non-null    float64
 34  0-28 DAYS TOTAL CT                  808 non-null    float64
 35  10-19 YRS FEMALE CT                 809 non-null    float64
 36  10-19 YRS MALE CT                   810 non-null    float64
 37  10-19 YRS CT TOTAL                  808 non-null    float64
 38  20 + YRS FEMALE CT                  808 non-null    float64
 39  20 + YRS MALE CT                    808 non-null    float64
 40  20 + YRS CT TOTAL                   807 non-null    float64
 41  29DAYS - 4YRS FEMALE CT             809 non-null    float64
 42  29 DAYS - 4YRS MALE CT              809 non-null    float64
 43  29 DAYS - 4YRS CT TOTAL             807 non-null    float64
 44  5-9YRS FEMALE CT                    809 non-null    float64
 45  5-9YRS MALE CT                      809 non-null    float64
 46  5-9YRS CT TOTAL                     807 non-null    float64
 47  PREG 10-19YRS                       809 non-null    float64
 48  PREG 20 + YRS                       809 non-null    float64
 49  TOTAL PREG                          806 non-null    float64
 50  TOTAL CASES FEMALE                  810 non-null    float64
 51  TOTAL CASES MALE                    810 non-null    float64
 52  GRAND TOTAL CASES                   808 non-null    float64
 53  <5YRS FEMALES TOTAL                 809 non-null    float64
 54  <5YRS MALE TOTAL                    810 non-null    float64
 55  < 5YRS GRAND TOTAL                  810 non-null    float64
 56  AREA(Km2)                           798 non-null    float64
 57  TOTAL POPULATION                    803 non-null    object
 58  POPULATION DENSITY(People per km2)  803 non-null    object
 59  CORDINATES (LATITUDE ° N)           749 non-null    object
 60  CORDINATES (LONGITUDE ° E)          749 non-null    object
 61  Year                                848 non-null    int64
 62  10-19 YRS TOTAL                     162 non-null    float64
 63  29DAYS-4YRS MALE                    162 non-null    float64
 64  20+ (B/S &RDT) MALE                 162 non-null    float64
dtypes: float64(54), int64(1), object(10)
memory usage: 430.8+ KB

In [85]:
# Dictionary of columns that should be merged
merge_map = {
    "20+ (B/S &RDT) MALE": "20+ (B/S & RDT) MALE",
    "29DAYS-4YRS MALE": "29DAYS - 4YRS MALE",
    "10-19 YRS TOTAL": "10-19YRS TOTAL"
}

for bad_col, good_col in merge_map.items():
    if bad_col in master_df.columns and good_col in master_df.columns:
        # Merge values where good_col is missing
        master_df[good_col] = master_df[good_col].fillna(master_df[bad_col])
        # Drop the redundant col
        master_df = master_df.drop(columns=[bad_col])

In [69]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 808 entries, 0 to 807
Data columns (total 65 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Region                              805 non-null    object
 1   District                            807 non-null    object
 2   0-28 DAYS FEMALE                    806 non-null    float64
 3   0-28 DAYS MALE                      806 non-null    float64
 4   0-28 DAYS TOTAL                     807 non-null    float64
 5   10-19 YEARS FEMALE                  806 non-null    float64
 6   10-19 YEARS MALE                    806 non-null    float64
 7   10-19YRS TOTAL                      645 non-null    float64
 8   20+ YRS FEMALE                      806 non-null    float64
 9   20+ YRS MALE                        806 non-null    float64
 10  20+ YRS TOTAL                       807 non-null    float64
 11  5-9YRS FEMALE                       806 non-null    float64
 12  5-9YRS MALE                         805 non-null    float64
 13  5-9YRS TOTAL                        807 non-null    float64
 14  29 DAYS-4YRS FEMALE                 806 non-null    float64
 15  29DAYS - 4YRS MALE                  644 non-null    float64
 16  29 DAYS - 4YRS TOTAL                807 non-null    float64
 17  0-28 DAYS (B/S & RDT) FEMALE        806 non-null    float64
 18  0-28 DAYS (B/S & RDT) MALE          805 non-null    float64
 19  0-28 DAYS (B/S & RDT) TOTAL         805 non-null    float64
 20  10-19 YRS (B/S & RDT) FEMALE        806 non-null    float64
 21  10-19 YRS (B/S & RDT) MALE          806 non-null    float64
 22  10-19 YRS (B/S & RDT) TOTAL         805 non-null    float64
 23  20+ (B/S &RDT) FEMALE               806 non-null    float64
 24  20+ (B/S & RDT) MALE                644 non-null    float64
 25  20 + (B/S & RDT) TOTAL              805 non-null    float64
 26  29DAYS-4YRS (B/S & RDT) FEMALE      806 non-null    float64
 27  29DAYS-4YRS (B/S & RDT) MALE        806 non-null    float64
 28  29DAYS-4 YRS (B/S & RDT) TOTAL      805 non-null    float64
 29  5-9YRS (B/S & RDT) FEMALE           806 non-null    float64
 30  5-9YRS (B/S & RDT) MALE             806 non-null    float64
 31  5-9YRS (B/S & RDT) TOTAL            805 non-null    float64
 32  0-28 DAYS FEMALE CT                 806 non-null    float64
 33  0-28 DAYS MALE CT                   806 non-null    float64
 34  0-28 DAYS TOTAL CT                  806 non-null    float64
 35  10-19 YRS FEMALE CT                 806 non-null    float64
 36  10-19 YRS MALE CT                   807 non-null    float64
 37  10-19 YRS CT TOTAL                  806 non-null    float64
 38  20 + YRS FEMALE CT                  805 non-null    float64
 39  20 + YRS MALE CT                    805 non-null    float64
 40  20 + YRS CT TOTAL                   805 non-null    float64
 41  29DAYS - 4YRS FEMALE CT             806 non-null    float64
 42  29 DAYS - 4YRS MALE CT              806 non-null    float64
 43  29 DAYS - 4YRS CT TOTAL             805 non-null    float64
 44  5-9YRS FEMALE CT                    806 non-null    float64
 45  5-9YRS MALE CT                      806 non-null    float64
 46  5-9YRS CT TOTAL                     805 non-null    float64
 47  PREG 10-19YRS                       806 non-null    float64
 48  PREG 20 + YRS                       806 non-null    float64
 49  TOTAL PREG                          804 non-null    float64
 50  TOTAL CASES FEMALE                  807 non-null    float64
 51  TOTAL CASES MALE                    807 non-null    float64
 52  GRAND TOTAL CASES                   806 non-null    float64
 53  <5YRS FEMALES TOTAL                 806 non-null    float64
 54  <5YRS MALE TOTAL                    807 non-null    float64
 55  < 5YRS GRAND TOTAL                  807 non-null    float64
 56  AREA(Km2)                           797 non-null    float64
 57  TOTAL POPULATION                    803 non-null    object
 58  POPULATION DENSITY(People per km2)  803 non-null    object
 59  CORDINATES (LATITUDE ° N)           749 non-null    object
 60  CORDINATES (LONGITUDE ° E)          749 non-null    object
 61  Year                                808 non-null    int64
 62  10-19 YRS TOTAL                     162 non-null    float64
 63  29DAYS-4YRS MALE                    162 non-null    float64
 64  20+ (B/S &RDT) MALE                 162 non-null    float64
dtypes: float64(58), int64(1), object(6)
memory usage: 410.4+ KB

In [78]:
print(master_df[['Year'] = 2020, ['TOTAL PREG']]).head()

SyntaxError: invalid syntax (2408324627.py, line 1)

In [65]:

all_files = glob.glob("MALARIA EDA/Malaria data/Malaria data *.csv")
print("Files found:", all_files)

Files found: ['MALARIA EDA/Malaria data\\Malaria data 2020.csv', 'MALARIA EDA/Malaria data\\Malaria data 2021.csv', 'MALARIA EDA/Malaria data\\Malaria data 2022.csv', 'MALARIA EDA/Malaria data\\Malaria data 2023.csv', 'MALARIA EDA/Malaria data\\Malaria data 2024.csv']

In [66]:
import glob
import pandas as pd
import os

def clean_columns(df):
    df.columns = df.columns.str.strip()
    df.columns = df.columns.str.replace(r"\s+", " ", regex=True)
    return df

# Use relative path without 1033 if Jupyter starts in that folder
all_files = glob.glob("MALARIA EDA/Malaria data/Malaria data *.csv")

print("Files found:", all_files)  # Debug check

dfs = []
for file in all_files:
    df = pd.read_csv(file)
    df = clean_columns(df)

    # Extract year from filename
    year = os.path.splitext(os.path.basename(file))[0].split()[-1]
    df["Year"] = int(year)

    dfs.append(df)

master_df = pd.concat(dfs, ignore_index=True)

print(master_df["Year"].value_counts())
print(master_df.head())

Files found: ['MALARIA EDA/Malaria data\\Malaria data 2020.csv', 'MALARIA EDA/Malaria data\\Malaria data 2021.csv', 'MALARIA EDA/Malaria data\\Malaria data 2022.csv', 'MALARIA EDA/Malaria data\\Malaria data 2023.csv', 'MALARIA EDA/Malaria data\\Malaria data 2024.csv']
Year
2021    163
2024    162
2020    161
2022    161
2023    161
Name: count, dtype: int64
      Region           District  0-28 DAYS FEMALE  0-28 DAYS MALE  \
0   Karamoja      Abim District               6.0             7.0
1     Acholi             Acholi             316.0           338.0
2  West Nile  Adjumani District              14.0            10.0
3     Acholi     Agago District              46.0            66.0
4      Lango  Alebtong District               3.0             5.0

   0-28 DAYS TOTAL  10-19 YEARS FEMALE  10-19 YEARS MALE  10-19YRS TOTAL  \
0             13.0             16161.0            9062.0         25223.0
1            654.0            365422.0          214763.0        580185.0
2             24.0             68996.0           51991.0        120987.0
3            112.0             66256.0           39123.0        105379.0
4              8.0              7110.0            3851.0         10961.0

   20+ YRS FEMALE  20+ YRS MALE  ...  POPULATION DENSITY(People per km2)  \
0         16507.0        8054.0  ...                         55.79144888
1        456269.0      123147.0  ...                         63.34007043
2         60160.0       28387.0  ...                         55.79144888
3         58935.0       20260.0  ...                          78.0367573
4          9974.0        3515.0  ...                          169.253873

   CORDINATES (LATITUDE ° N)  CORDINATES (LONGITUDE ° E)  Year  \
0                     2.7067                     33.6595  2020
1                        NaN                         NaN  2020
2                     3.2549                     31.7195  2020
3                     2.9251                     33.3486  2020
4                     2.2914                     33.2139  2020

   10-19 YRS TOTAL  29DAYS-4YRS MALE  20+ (B/S &RDT) MALE  Unnamed: 64  \
0              NaN               NaN                  NaN          NaN
1              NaN               NaN                  NaN          NaN
2              NaN               NaN                  NaN          NaN
3              NaN               NaN                  NaN          NaN
4              NaN               NaN                  NaN          NaN

   Unnamed: 65  Unnamed: 66
0          NaN          NaN
1          NaN          NaN
2          NaN          NaN
3          NaN          NaN
4          NaN          NaN

[5 rows x 71 columns]

In [ ]:
master_df.info()

In [79]:
import glob
import pandas as pd
import os  # You need to import os for the path functions

def clean_columns(df):
    df.columns = df.columns.str.strip()  # remove leading/trailing spaces
    df.columns = df.columns.str.replace(r"\s+", " ", regex=True)  # normalize multiple spaces to one
    return df

# Collect all CSVs
all_files = glob.glob("MALARIA EDA/Malaria data/*.csv")

dfs = []
for file in all_files:
    df = pd.read_csv(file)
    df = clean_columns(df)
    
    # Extract year from file name (this needs to be inside the loop)
    year = os.path.splitext(os.path.basename(file))[0].split()[-1]
    df["Year"] = int(year)
    
    dfs.append(df)  # This also needs to be inside the loop

# Combine into one master DataFrame
master_df = pd.concat(dfs, ignore_index=True)

print(master_df[["Year"]].head(20))
print(master_df.columns.tolist())

    Year
0   2020
1   2020
2   2020
3   2020
4   2020
5   2020
6   2020
7   2020
8   2020
9   2020
10  2020
11  2020
12  2020
13  2020
14  2020
15  2020
16  2020
17  2020
18  2020
19  2020
['Region', 'District', '0-28 DAYS FEMALE', '0-28 DAYS MALE', '0-28 DAYS TOTAL', '10-19 YEARS FEMALE', '10-19 YEARS MALE', '10-19YRS TOTAL', '20+ YRS FEMALE', '20+ YRS MALE', '20+ YRS TOTAL', '5-9YRS FEMALE', '5-9YRS MALE', '5-9YRS TOTAL', '29 DAYS-4YRS FEMALE', '29DAYS - 4YRS MALE', '29 DAYS - 4YRS TOTAL', '0-28 DAYS (B/S & RDT) FEMALE', '0-28 DAYS (B/S & RDT) MALE', '0-28 DAYS (B/S & RDT) TOTAL', '10-19 YRS (B/S & RDT) FEMALE', '10-19 YRS (B/S & RDT) MALE', '10-19 YRS (B/S & RDT) TOTAL', '20+ (B/S &RDT) FEMALE', '20+ (B/S & RDT) MALE', '20 + (B/S & RDT) TOTAL', '29DAYS-4YRS (B/S & RDT) FEMALE', '29DAYS-4YRS (B/S & RDT) MALE', '29DAYS-4 YRS (B/S & RDT) TOTAL', '5-9YRS (B/S & RDT) FEMALE', '5-9YRS (B/S & RDT) MALE', '5-9YRS (B/S & RDT) TOTAL', '0-28 DAYS FEMALE CT', '0-28 DAYS MALE CT', '0-28 DAYS TOTAL CT', '10-19 YRS FEMALE CT', '10-19 YRS MALE CT', '10-19 YRS CT TOTAL', '20 + YRS FEMALE CT', '20 + YRS MALE CT', '20 + YRS CT TOTAL', '29DAYS - 4YRS FEMALE CT', '29 DAYS - 4YRS MALE CT', '29 DAYS - 4YRS CT TOTAL', '5-9YRS FEMALE CT', '5-9YRS MALE CT', '5-9YRS CT TOTAL', 'PREG 10-19YRS', 'PREG 20 + YRS', 'TOTAL PREG', 'TOTAL CASES FEMALE', 'TOTAL CASES MALE', 'GRAND TOTAL CASES', '<5YRS FEMALES TOTAL', '<5YRS MALE TOTAL', '< 5YRS GRAND TOTAL', 'POPULATION IN 2014', 'POPULATION IN 2024', 'AREA(Km2)', 'ANNUAL GROWTH RATE[Pt\u200b=P0\u200b×(1+r)t]', 'TOTAL POPULATION', 'POPULATION DENSITY(People per km2)', 'CORDINATES (LATITUDE ° N)', 'CORDINATES (LONGITUDE ° E)', 'Year', '10-19 YRS TOTAL', '29DAYS-4YRS MALE', '20+ (B/S &RDT) MALE', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66']

In [80]:
# Check how many unique years are in your data
print("Unique years in dataset:", master_df['Year'].unique())

Unique years in dataset: [2020 2021 2022 2023 2024]

In [81]:
# Check the distribution of rows per year
print("\nNumber of rows per year:")
print(master_df['Year'].value_counts().sort_index())

Number of rows per year:
Year
2020    161
2021    163
2022    161
2023    161
2024    162
Name: count, dtype: int64

In [82]:
# Check a sample from each year to verify the data is different
print("\nSample from each year:")
for year in sorted(master_df['Year'].unique()):
    sample = master_df[master_df['Year'] == year].head(2)
    print(f"\nYear {year} sample:")
    print(sample[['District', 'GRAND TOTAL CASES', 'Year']])

Sample from each year:

Year 2020 sample:
        District  GRAND TOTAL CASES  Year
0  Abim District            81614.0  2020
1         Acholi          1659514.0  2020

Year 2021 sample:
          District  GRAND TOTAL CASES  Year
161  Abim District            84765.0  2021
162         Acholi          1146203.0  2021

Year 2022 sample:
          District  GRAND TOTAL CASES  Year
324  Abim District             1520.0  2022
325         Acholi            32202.0  2022

Year 2023 sample:
          District  GRAND TOTAL CASES  Year
485  Abim District            69331.0  2023
486         Acholi          1400389.0  2023

Year 2024 sample:
          District  GRAND TOTAL CASES  Year
646  Abim District            81614.0  2024
647         Acholi          1659514.0  2024

In [86]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 808 entries, 0 to 807
Data columns (total 62 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Region                              805 non-null    object
 1   District                            807 non-null    object
 2   0-28 DAYS FEMALE                    806 non-null    float64
 3   0-28 DAYS MALE                      806 non-null    float64
 4   0-28 DAYS TOTAL                     807 non-null    float64
 5   10-19 YEARS FEMALE                  806 non-null    float64
 6   10-19 YEARS MALE                    806 non-null    float64
 7   10-19YRS TOTAL                      807 non-null    float64
 8   20+ YRS FEMALE                      806 non-null    float64
 9   20+ YRS MALE                        806 non-null    float64
 10  20+ YRS TOTAL                       807 non-null    float64
 11  5-9YRS FEMALE                       806 non-null    float64
 12  5-9YRS MALE                         805 non-null    float64
 13  5-9YRS TOTAL                        807 non-null    float64
 14  29 DAYS-4YRS FEMALE                 806 non-null    float64
 15  29DAYS - 4YRS MALE                  806 non-null    float64
 16  29 DAYS - 4YRS TOTAL                807 non-null    float64
 17  0-28 DAYS (B/S & RDT) FEMALE        806 non-null    float64
 18  0-28 DAYS (B/S & RDT) MALE          805 non-null    float64
 19  0-28 DAYS (B/S & RDT) TOTAL         805 non-null    float64
 20  10-19 YRS (B/S & RDT) FEMALE        806 non-null    float64
 21  10-19 YRS (B/S & RDT) MALE          806 non-null    float64
 22  10-19 YRS (B/S & RDT) TOTAL         805 non-null    float64
 23  20+ (B/S &RDT) FEMALE               806 non-null    float64
 24  20+ (B/S & RDT) MALE                806 non-null    float64
 25  20 + (B/S & RDT) TOTAL              805 non-null    float64
 26  29DAYS-4YRS (B/S & RDT) FEMALE      806 non-null    float64
 27  29DAYS-4YRS (B/S & RDT) MALE        806 non-null    float64
 28  29DAYS-4 YRS (B/S & RDT) TOTAL      805 non-null    float64
 29  5-9YRS (B/S & RDT) FEMALE           806 non-null    float64
 30  5-9YRS (B/S & RDT) MALE             806 non-null    float64
 31  5-9YRS (B/S & RDT) TOTAL            805 non-null    float64
 32  0-28 DAYS FEMALE CT                 806 non-null    float64
 33  0-28 DAYS MALE CT                   806 non-null    float64
 34  0-28 DAYS TOTAL CT                  806 non-null    float64
 35  10-19 YRS FEMALE CT                 806 non-null    float64
 36  10-19 YRS MALE CT                   807 non-null    float64
 37  10-19 YRS CT TOTAL                  806 non-null    float64
 38  20 + YRS FEMALE CT                  805 non-null    float64
 39  20 + YRS MALE CT                    805 non-null    float64
 40  20 + YRS CT TOTAL                   805 non-null    float64
 41  29DAYS - 4YRS FEMALE CT             806 non-null    float64
 42  29 DAYS - 4YRS MALE CT              806 non-null    float64
 43  29 DAYS - 4YRS CT TOTAL             805 non-null    float64
 44  5-9YRS FEMALE CT                    806 non-null    float64
 45  5-9YRS MALE CT                      806 non-null    float64
 46  5-9YRS CT TOTAL                     805 non-null    float64
 47  PREG 10-19YRS                       806 non-null    float64
 48  PREG 20 + YRS                       806 non-null    float64
 49  TOTAL PREG                          804 non-null    float64
 50  TOTAL CASES FEMALE                  807 non-null    float64
 51  TOTAL CASES MALE                    807 non-null    float64
 52  GRAND TOTAL CASES                   806 non-null    float64
 53  <5YRS FEMALES TOTAL                 806 non-null    float64
 54  <5YRS MALE TOTAL                    807 non-null    float64
 55  < 5YRS GRAND TOTAL                  807 non-null    float64
 56  AREA(Km2)                           797 non-null    float64
 57  TOTAL POPULATION                    803 non-null    object
 58  POPULATION DENSITY(People per km2)  803 non-null    object
 59  CORDINATES (LATITUDE ° N)           749 non-null    object
 60  CORDINATES (LONGITUDE ° E)          749 non-null    object
 61  Year                                808 non-null    int64
dtypes: float64(55), int64(1), object(6)
memory usage: 391.5+ KB